### ISSUE TITLE
fix tests so they run on python 2.6 and 3.X

### ISSUE THREAD

**Issue by Itxaka** [pyapi-gitlab/pyapi-gitlab#41]

**Comment by jirihnidek** [comment]
Your unit tests code includes username and password. It is not wise. You can make it more secure:

http://about.travis-ci.org/docs/user/build-configuration/#Secure-environment-variables

**Comment by samrocketman** [comment]
Re: @jirihnidek
Specifically here https://github.com/Itxaka/pyapi-gitlab/blob/6.1/tests/gitlab_test.py#L14-L16

**Comment by jirihnidek** [comment]
Re: @sag47 exactly :+1:

**Comment by Itxaka** [comment]
@jirihnidek @sag47 True! Will try to have a look at the Travis CI docs tomorrow and fix it. Thanks for the heads up!

**Comment by Itxaka** [comment]
Should be fixed now, it runs on python 2.6, 2.7 and 3 and has protected environment variables instead of user/pass embedded :dancers:

**Comment by samrocketman** [comment]
@Itxaka I would still consider this problem not resolved until you change the password and authentication token on the server.  Please note someone can easily [look at your edit history and see the user and password](https://github.com/Itxaka/pyapi-gitlab/blob/4d778d780161869550d8e514cdc50df2398f844e/tests/gitlab_test.py#L14-L26).
1. Change the password for `pyapi-gitlab` user.
2. Generate a new private token from _Profile settings > Accounts > Private token_.

I recommend using the `uuidgen` command to generate a random password for you to use.

**Comment by Itxaka** [comment]
@sag47 Done!
